export const routes = {
  home: "/",
  signUp: "/sign-up",
  login: "/login",

  app: {
    root: "/app",
    dashboard: "/app",
    kyc: "/app/kyc",
    kycStatus: "/app/kyc/status",
    wallet: "/app/wallet",
    addMoney: "/app/add-money",
    addMoneyCreditCard: "/app/add-money/credit-card",
    addMoneyUpi: "/app/add-money/upi",
    addMoneyBankTransfer: "/app/add-money/bank-transfer",
    fundingRequest: (id: string) => `/app/funding-requests/${id}`,
    fundingRequestSuccess: (id: string) => `/app/funding-requests/${id}/success`,
    transactions: "/app/transactions",
    transaction: (id: string) => `/app/transactions/${id}`,
    services: "/app/services",
    profile: "/app/profile",
    support: "/app/support",
  },

  operations: {
    root: "/operations",
    overview: "/operations",
    fundingQueue: "/operations/funding",
    fundingDetail: (id: string) => `/operations/funding/${id}`,
    kycQueue: "/operations/kyc",
    kycDetail: (id: string) => `/operations/kyc/${id}`,
    customers: "/operations/customers",
    wallets: "/operations/wallets",
    transactions: "/operations/transactions",
    reconciliation: "/operations/reconciliation",
    support: "/operations/support",
    reports: "/operations/reports",
  },

  admin: {
    root: "/admin",
    dashboard: "/admin",
    customers: "/admin/customers",
    operationsUsers: "/admin/operations",
    funding: "/admin/funding",
    wallets: "/admin/wallets",
    transactions: "/admin/transactions",
    kyc: "/admin/kyc",
    paymentMethods: "/admin/payment-methods",
    fees: "/admin/fees",
    limits: "/admin/limits",
    roles: "/admin/roles",
    reports: "/admin/reports",
    reconciliation: "/admin/reconciliation",
    auditLogs: "/admin/audit-logs",
    settings: "/admin/settings",
  },
} as const
